"""mcp_oauth_tables

Revision ID: b71ff816f398
Revises: e99074fad2c7
Create Date: 2026-04-22 11:41:10.044198

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "b71ff816f398"
down_revision: Union[str, Sequence[str], None] = "initial_oauth_tables"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oauth_authorization_codes",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("client_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("redirect_uri", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("redirect_uri_provided_explicitly", sa.Boolean(), nullable=False),
        sa.Column("code_challenge", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("scopes", sa.JSON(), nullable=False),
        sa.Column("resource", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["client_id"], ["oauth_clients.client_id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_oauth_authorization_codes_client_id"),
        "oauth_authorization_codes",
        ["client_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_oauth_authorization_codes_code"),
        "oauth_authorization_codes",
        ["code"],
        unique=True,
    )
    op.create_index(
        op.f("ix_oauth_authorization_codes_user_id"),
        "oauth_authorization_codes",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "oauth_tokens",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("token_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("token_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("client_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("scopes", sa.JSON(), nullable=False),
        sa.Column("resource", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("pair_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_oauth_tokens_client_id"), "oauth_tokens", ["client_id"], unique=False)
    op.create_index(op.f("ix_oauth_tokens_pair_id"), "oauth_tokens", ["pair_id"], unique=False)
    op.create_index(op.f("ix_oauth_tokens_token_hash"), "oauth_tokens", ["token_hash"], unique=True)
    op.create_index(op.f("ix_oauth_tokens_user_id"), "oauth_tokens", ["user_id"], unique=False)
    op.drop_table("oauth_pending_requests")
    op.drop_index(op.f("ix_oauth_auth_codes_user_id"), table_name="oauth_auth_codes")
    op.drop_table("oauth_auth_codes")
    op.drop_index(op.f("ix_oauth_refresh_tokens_user_id"), table_name="oauth_refresh_tokens")
    op.drop_table("oauth_refresh_tokens")
    op.add_column(
        "oauth_clients",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
    )
    op.add_column(
        "oauth_clients",
        sa.Column("client_secret_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "oauth_clients",
        sa.Column(
            "client_id_issued_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
    )
    op.add_column("oauth_clients", sa.Column("redirect_uris", sa.JSON(), nullable=False))
    op.add_column(
        "oauth_clients", sa.Column("client_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.add_column("oauth_clients", sa.Column("grant_types", sa.JSON(), nullable=False))
    op.add_column("oauth_clients", sa.Column("response_types", sa.JSON(), nullable=False))
    op.add_column(
        "oauth_clients", sa.Column("scope", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.add_column(
        "oauth_clients",
        sa.Column("token_endpoint_auth_method", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.create_index(op.f("ix_oauth_clients_client_id"), "oauth_clients", ["client_id"], unique=True)
    op.drop_column("oauth_clients", "client_data")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "oauth_clients", sa.Column("client_data", sa.TEXT(), autoincrement=False, nullable=False)
    )
    op.drop_index(op.f("ix_oauth_clients_client_id"), table_name="oauth_clients")
    op.drop_column("oauth_clients", "token_endpoint_auth_method")
    op.drop_column("oauth_clients", "scope")
    op.drop_column("oauth_clients", "response_types")
    op.drop_column("oauth_clients", "grant_types")
    op.drop_column("oauth_clients", "client_name")
    op.drop_column("oauth_clients", "redirect_uris")
    op.drop_column("oauth_clients", "client_id_issued_at")
    op.drop_column("oauth_clients", "client_secret_hash")
    op.drop_column("oauth_clients", "id")
    op.create_table(
        "oauth_refresh_tokens",
        sa.Column("token", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("client_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("scopes", sa.TEXT(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("oauth_refresh_tokens_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("token", name=op.f("oauth_refresh_tokens_pkey")),
    )
    op.create_index(
        op.f("ix_oauth_refresh_tokens_user_id"), "oauth_refresh_tokens", ["user_id"], unique=False
    )
    op.create_table(
        "oauth_auth_codes",
        sa.Column("code", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("client_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("scopes", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "expires_at", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False
        ),
        sa.Column("code_challenge", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("redirect_uri", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "redirect_uri_provided_explicitly", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
        sa.Column("resource", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("oauth_auth_codes_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("code", name=op.f("oauth_auth_codes_pkey")),
    )
    op.create_index(
        op.f("ix_oauth_auth_codes_user_id"), "oauth_auth_codes", ["user_id"], unique=False
    )
    op.create_table(
        "oauth_pending_requests",
        sa.Column("request_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("client_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("redirect_uri", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "redirect_uri_provided_explicitly", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
        sa.Column("code_challenge", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("state", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("scopes", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("resource", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("request_id", name=op.f("oauth_pending_requests_pkey")),
    )
    op.drop_index(op.f("ix_oauth_tokens_user_id"), table_name="oauth_tokens")
    op.drop_index(op.f("ix_oauth_tokens_token_hash"), table_name="oauth_tokens")
    op.drop_index(op.f("ix_oauth_tokens_pair_id"), table_name="oauth_tokens")
    op.drop_index(op.f("ix_oauth_tokens_client_id"), table_name="oauth_tokens")
    op.drop_table("oauth_tokens")
    op.drop_index(
        op.f("ix_oauth_authorization_codes_user_id"), table_name="oauth_authorization_codes"
    )
    op.drop_index(op.f("ix_oauth_authorization_codes_code"), table_name="oauth_authorization_codes")
    op.drop_index(
        op.f("ix_oauth_authorization_codes_client_id"), table_name="oauth_authorization_codes"
    )
    op.drop_table("oauth_authorization_codes")
    # ### end Alembic commands ###
