"""add_ocr_enabled_to_ai_providers

Revision ID: ce90f9fda434
Revises: wallet_cascade_deletes
Create Date: 2026-04-12 10:02:49.029105

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "ce90f9fda434"
down_revision: Union[str, Sequence[str], None] = "wallet_cascade_deletes"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ai_providers",
        sa.Column("ocr_enabled", sa.Boolean(), nullable=False, server_default=sa.text("true")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ai_providers", "ocr_enabled")
    # ### end Alembic commands ###
