"""add transaction links

Revision ID: 6a6f523a03b3
Revises: 81b3b1edb12b
Create Date: 2026-04-30 12:00:48.278960

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "6a6f523a03b3"
down_revision: Union[str, Sequence[str], None] = "81b3b1edb12b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transaction_links",
        sa.Column("transaction_id_a", sa.Uuid(), nullable=False),
        sa.Column("transaction_id_b", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["transaction_id_a"], ["transactions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["transaction_id_b"], ["transactions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("transaction_id_a", "transaction_id_b"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transaction_links")
    # ### end Alembic commands ###
