"""add global_currency to users

Revision ID: f27b138cdc86
Revises: 7cbc1d5710de
Create Date: 2026-05-02 21:10:01.236479

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "f27b138cdc86"
down_revision: Union[str, Sequence[str], None] = "7cbc1d5710de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("global_currency", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "global_currency")
    # ### end Alembic commands ###
